# Generated by Django 3.1.4 on 2020-12-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_subscriber_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='hobby',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Game', 'Game'), ('Music', 'Music'), ('Society', 'Society'), ('Education', 'Education')], max_length=20, null=True),
        ),
    ]
